// Usage:
// - Contains launcher bindings for all built-in 1D cases.
// - Add new 1D cases here when you want them available in the unified backend.

#include "BuiltinLaunchers.h"
#include "Couette.h"
#include <cmath>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <iomanip>
#include <limits>
#include <locale>
#include <mutex>
#include <sstream>
#include <thread>
#include <functional>
#include <fstream>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>

#include "apps/support/CaseRunner1D.h"
#include "cases/1d/CouetteCase.h"
#include "cases/1d/ShockStructureCase.h"

namespace hymos {
namespace engine {
namespace {

template <typename App>
int RunInteractive(const std::string& control_script) {
  App app;
  return hymos::apps::CaseRunner1D<App>::Main(app, control_script.c_str());
}

template <typename App>
int RunBatch(const std::string& case_id,
             const std::string& case_label,
             const std::string& config_path) {
  RunWorkspace workspace(case_id, case_label, config_path);
  if (!workspace.Prepare()) {
    return 1;
  }
  App app;
  app.read_config(workspace.ConfigFilename());
  app.run();
  return 0;
}

}  // namespace

int RunCouetteInteractive(const std::string& control_script) {
  return RunInteractive<hymos::cases::oned::couette::app_t>(control_script);
}

int RunCouetteBatch(const std::string& config_path) {
  return RunBatch<hymos::cases::oned::couette::app_t>("couette", "Couette", config_path);
}

int RunShockStructureInteractive(const std::string& control_script) {
  return RunInteractive<hymos::cases::oned::shock_structure::app_t>(control_script);
}

int RunShockStructureBatch(const std::string& config_path) {
  return RunBatch<hymos::cases::oned::shock_structure::app_t>("shockstructure", "ShockStructure", config_path);
}

namespace {
std::mutex couette_memory_mutex;

std::string PreciseNumber(double value) {
  std::ostringstream os;
  os.imbue(std::locale::classic());
  os << std::setprecision(std::numeric_limits<double>::max_digits10) << value;
  return os.str();
}

struct CouetteEnvironment {
  typedef hymos::cases::oned::couette::Case Case;
  double temperature = Case::Temperature, kn = Case::Kn, pr = Case::Pr, ma = Case::Ma;
  double left_temperature = Case::LeftWallTemperature, left_u2 = Case::LeftWallU2;
  double right_temperature = Case::RightWallTemperature, right_u2 = Case::RightWallU2;
  int threads = omp_get_max_threads();
  ~CouetteEnvironment() {
    Case::Temperature = temperature; Case::Kn = kn; Case::Pr = pr; Case::Ma = ma;
    Case::LeftWallTemperature = left_temperature; Case::LeftWallU2 = left_u2;
    Case::RightWallTemperature = right_temperature; Case::RightWallU2 = right_u2;
    omp_set_num_threads(threads);
  }
};
}

bool ValidateCouetteLimits(const CouetteConfig& config, std::string* message) {
  if (config.order >= 3 && config.order < MAX_ORDER &&
      config.n_thread >= 1 && config.n_thread <= 256 &&
      config.mesh_type == 0 &&
      config.nx >= 8 && config.nx <= 4096 &&
      std::isfinite(config.temperature) && config.temperature > 0 &&
      std::isfinite(config.kn) && config.kn > 0 &&
      std::isfinite(config.pr) && config.pr > 0 &&
      std::isfinite(config.ma) && config.ma > 0 &&
      std::isfinite(config.mesh_left) &&
      std::isfinite(config.mesh_length) && config.mesh_length > 0 &&
      std::isfinite(config.tolerance) && config.tolerance > 0 &&
      std::isfinite(config.cfl) && config.cfl > 0 && config.cfl <= 1 &&
      std::isfinite(config.cfl_euler) && config.cfl_euler > 0 && config.cfl_euler <= 1 &&
      config.euler_steps >= 1 && config.euler_steps <= 10000 &&
      config.max_steps >= 1 && config.max_steps <= 100000) {
    return true;
  }
  if (message != NULL) {
    *message = "Expected ORDER in [3,49], n_thread in [1,256], Mesh/Type 0, "
               "nx in [8,4096], finite positive Temperature/Kn/Pr/Ma/Len/tolerance, "
               "finite L0, CFLs in (0,1], euler_steps in [1,10000], "
               "max_steps in [1,100000]";
  }
  return false;
}

void WriteLegacyDistribution(const hymos::cases::oned::couette::sol_t& solution,
                             const hymos::cases::oned::couette::mesh_t& mesh,
                             const std::string& path) {
  if (path.empty()) return;
  const std::string temporary = path + ".tmp";
  std::ofstream output(temporary.c_str(), std::ios::out | std::ios::trunc);
  if (!output) {
    throw std::runtime_error("cannot create legacy distribution output: " +
                             temporary);
  }
  output.precision(12);
  output << "% 1D distribution solution generated by HyMoS" << std::endl;
  output << "% column 1 = x, remaining values = full distribution data in internal storage order" << std::endl;
  for (size_t i = 0; i < solution.size(); ++i) {
    output << mesh.Center(i) << ' ';
    const hymos::cases::oned::couette::dis_t::Velocity& center =
        solution[i].Center();
    for (size_t j = 0; j < center.size(); ++j) output << center[j] << ' ';
    output << solution[i].Scaling() << ' ';
    for (hymos::cases::oned::couette::dis_t::ConstIterator coefficient =
             solution[i].begin();
         coefficient != solution[i].end(); ++coefficient) {
      output << *coefficient << ' ';
    }
    output << std::endl;
  }
  output.close();
  if (!output) {
    std::remove(temporary.c_str());
    throw std::runtime_error("cannot complete legacy distribution output: " +
                             temporary);
  }
  if (std::rename(temporary.c_str(), path.c_str()) != 0) {
    const std::string reason = std::strerror(errno);
    std::remove(temporary.c_str());
    throw std::runtime_error("cannot publish legacy distribution output " +
                             path + ": " + reason);
  }
}

CouetteResult SolveCouetteInternal(
    const CouetteConfig& config, const std::atomic<bool>* stop_requested,
    const std::function<void(unsigned int, double)>& progress =
        std::function<void(unsigned int, double)>()) {
  CouetteResult result;
  result.config = config;
  std::string validation_message;
  if (!ValidateCouetteLimits(config, &validation_message)) {
    result.status = CouetteStatus::InvalidConfig;
    result.message = validation_message;
    return result;
  }
  try {
    std::unique_lock<std::mutex> lock(couette_memory_mutex, std::try_to_lock);
    if (!lock.owns_lock()) {
      result.status = CouetteStatus::Busy;
      result.message = "Another in-memory Couette solve is active";
      return result;
    }
    CouetteEnvironment environment;
    std::map<std::string, std::string> entries = {
      {"System/ORDER", std::to_string(config.order)}, {"System/n_thread", std::to_string(config.n_thread)},
      {"System/Temperature", PreciseNumber(config.temperature)},
      {"Mesh/Type", std::to_string(config.mesh_type)}, {"Mesh/Nx", std::to_string(config.nx)},
      {"Mesh/L0", PreciseNumber(config.mesh_left)}, {"Mesh/Len", PreciseNumber(config.mesh_length)},
      {"Const/Kn", PreciseNumber(config.kn)}, {"Const/Pr", PreciseNumber(config.pr)},
      {"Const/Ma", PreciseNumber(config.ma)}, {"Error/Tol", PreciseNumber(config.tolerance)},
      {"Time/CFL", PreciseNumber(config.cfl)}, {"Time/CFL_HEs", PreciseNumber(config.cfl_euler)},
      {"SingleGridMethod/EulerEqsSolvingSteps", std::to_string(config.euler_steps)}
    };
    for (std::map<std::string, std::string>::const_iterator it = config.text_entries.begin(); it != config.text_entries.end(); ++it) entries[it->first] = it->second;
    ConfigFile cf(entries);
    hymos::cases::oned::couette::app_t app;
    app.read_config(cf);
    app.run_in_memory(config.max_steps, result.residual, stop_requested, progress);
    const auto& sol = app.solution_view();
    const auto& mesh = app.mesh_view();
    for (size_t i = 0; i < sol.size(); ++i) {
      double pv[5], flux[3];
      sol[i].PrimitiveVars(pv);
      sol[i].HeatFlux(flux);
      typedef hymos::cases::oned::couette::dis_t::Indices Index;
      const std::array<double, 3> stress = {{sol[i](Index(2,0,0),0),
                                            sol[i](Index(1,1,0),0),
                                            sol[i](Index(0,2,0),0)}};
      for (double value : pv) if (!std::isfinite(value)) throw std::runtime_error("non-finite field");
      for (double value : flux) if (!std::isfinite(value)) throw std::runtime_error("non-finite heat flux");
      for (double value : stress) if (!std::isfinite(value)) throw std::runtime_error("non-finite stress moment");
      result.x.push_back(mesh.Center(i));
      result.density.push_back(pv[0]);
      result.velocity.push_back({{pv[1],pv[2],pv[3]}});
      result.temperature.push_back(pv[4]);
      result.stress_moments.push_back(stress);
      result.heat_flux.push_back({{flux[0],flux[1]}});
    }
    WriteLegacyDistribution(sol, mesh, config.legacy_distribution_output_path);
    result.status = stop_requested != NULL && stop_requested->load()
                  ? CouetteStatus::Cancelled
                  : (result.residual.back() < config.tolerance
                       ? CouetteStatus::Converged : CouetteStatus::IterationLimit);
    result.message = result.status == CouetteStatus::Converged ? "Converged"
                   : (result.status == CouetteStatus::Cancelled ? "Stop requested"
                      : "Outer iteration limit reached");
    return result;
  } catch (const std::exception& ex) {
    result.message = ex.what();
  } catch (const std::string& ex) {
    result.message = ex;
  } catch (...) {
    result.message = "Unknown solver failure";
  }
  CouetteResult failed;
  failed.config = config;
  failed.message = result.message;
  return failed;
}


namespace {

bool ReadInt(const ConfigSnapshot& snapshot, const char* key, int* value,
             ConfigValidation* validation) {
  const std::map<std::string, std::string>::const_iterator found =
      snapshot.entries.find(key);
  if (found == snapshot.entries.end()) {
    validation->errors.push_back(std::string("missing ") + key);
    return false;
  }
  char* end = NULL;
  errno = 0;
  const long parsed = std::strtol(found->second.c_str(), &end, 10);
  if (errno != 0 || end == found->second.c_str() || *end != '\0' ||
      parsed < std::numeric_limits<int>::min() ||
      parsed > std::numeric_limits<int>::max()) {
    validation->errors.push_back(std::string("invalid integer ") + key);
    return false;
  }
  *value = static_cast<int>(parsed);
  return true;
}

bool ReadDouble(const ConfigSnapshot& snapshot, const char* key, double* value,
                ConfigValidation* validation) {
  const std::map<std::string, std::string>::const_iterator found =
      snapshot.entries.find(key);
  if (found == snapshot.entries.end()) {
    validation->errors.push_back(std::string("missing ") + key);
    return false;
  }
  char* end = NULL;
  errno = 0;
  const double parsed = std::strtod(found->second.c_str(), &end);
  if (errno != 0 || end == found->second.c_str() || *end != '\0' ||
      !std::isfinite(parsed)) {
    validation->errors.push_back(std::string("invalid finite number ") + key);
    return false;
  }
  *value = parsed;
  return true;
}

bool ReadOptionalWallDouble(const ConfigSnapshot& snapshot, const char* key,
                            double fallback, bool strictly_positive,
                            ConfigValidation* validation) {
  const std::map<std::string, std::string>::const_iterator found =
      snapshot.entries.find(key);
  if (found == snapshot.entries.end()) return std::isfinite(fallback) &&
      (!strictly_positive || fallback > 0);
  char* end = NULL;
  errno = 0;
  const double parsed = std::strtod(found->second.c_str(), &end);
  if (errno != 0 || end == found->second.c_str() || *end != '\0' ||
      !std::isfinite(parsed) || (strictly_positive && parsed <= 0)) {
    validation->errors.push_back(std::string("invalid ") +
        (strictly_positive ? "positive" : "finite") + " number " + key);
    return false;
  }
  return true;
}

}  // namespace

ConfigValidation BuildCouetteConfig(const ConfigSnapshot& snapshot,
                                    CouetteConfig* config) {
  ConfigValidation validation;
  validation.canonical_case_id = "couette";
  if (snapshot.case_id != "couette") {
    validation.errors.push_back("Couette backend requires a couette configuration snapshot");
    return validation;
  }
  if (config == NULL) {
    validation.errors.push_back("output configuration is null");
    return validation;
  }

  int order = 0, threads = 0, mesh_type = 0, fim = 0;
  int euler_steps = 0;
  double nx_as_double = 0.0, kn = 0.0, pr = 0.0, tolerance = 0.0;
  double cfl = 0.0, cfl_euler = 0.0, temperature = 0.0, ma = 1.0;
  double left = 0.0, length = 0.0;
  ReadInt(snapshot, "System/ORDER", &order, &validation);
  ReadInt(snapshot, "System/n_thread", &threads, &validation);
  ReadInt(snapshot, "Mesh/Type", &mesh_type, &validation);
  ReadDouble(snapshot, "Mesh/Nx", &nx_as_double, &validation);
  ReadDouble(snapshot, "Mesh/L0", &left, &validation);
  ReadDouble(snapshot, "Mesh/Len", &length, &validation);
  ReadDouble(snapshot, "Const/Kn", &kn, &validation);
  ReadDouble(snapshot, "Const/Pr", &pr, &validation);
  ReadDouble(snapshot, "Error/Tol", &tolerance, &validation);
  ReadDouble(snapshot, "Time/CFL", &cfl, &validation);
  ReadDouble(snapshot, "Time/CFL_HEs", &cfl_euler, &validation);
  ReadInt(snapshot, "SingleGridMethod/EulerEqsSolvingSteps", &euler_steps, &validation);
  ReadDouble(snapshot, "System/Temperature", &temperature, &validation);
  // Ma is a legacy Couette input with no numerical effect. Keep accepting it
  // when present, but do not require it in new planar-wall configurations.
  if (snapshot.entries.find("Const/Ma") != snapshot.entries.end())
    ReadDouble(snapshot, "Const/Ma", &ma, &validation);
  ReadInt(snapshot, "Solver/FIM", &fim, &validation);
  const std::map<std::string, std::string>::const_iterator solver =
      snapshot.entries.find("Solver/SolverType");
  if (solver == snapshot.entries.end()) {
    validation.errors.push_back("missing Solver/SolverType");
  } else if (solver->second != "single" && solver->second != "nmg" && solver->second != "NMG" && solver->second != "multigrid") {
    validation.errors.push_back("currently supported Solver/SolverType is single or nmg");
  }
  if (!validation.errors.empty()) return validation;

  const int nx = static_cast<int>(nx_as_double);
  if (nx_as_double != static_cast<double>(nx)) {
    validation.errors.push_back("Mesh/Nx must be an integer");
  }
  if (order < 3 || order >= MAX_ORDER)
    validation.errors.push_back("System/ORDER must be in [3,49]");
  if (threads < 1 || threads > 256)
    validation.errors.push_back("System/n_thread must be in [1,256]");
  if (fim < 1 || fim > 3) validation.errors.push_back("Solver/FIM must be 1, 2, or 3");
  if (pr != 1.0) validation.errors.push_back("Const/Pr must be 1 for the fixed BGK model");
  ReadOptionalWallDouble(snapshot, "LeftWall/Temperature", 1.0, true, &validation);
  ReadOptionalWallDouble(snapshot, "RightWall/Temperature", 1.0, true, &validation);
  ReadOptionalWallDouble(snapshot, "LeftWall/TangentialVelocity", -0.62885, false, &validation);
  ReadOptionalWallDouble(snapshot, "RightWall/TangentialVelocity", 0.62885, false, &validation);
  if (!validation.errors.empty()) return validation;

  CouetteConfig candidate;
  candidate.order = order;
  candidate.n_thread = threads;
  candidate.mesh_type = mesh_type;
  candidate.nx = nx;
  candidate.temperature = temperature;
  candidate.kn = kn;
  candidate.pr = pr;
  candidate.ma = ma;
  candidate.mesh_left = left;
  candidate.mesh_length = length;
  candidate.tolerance = tolerance;
  candidate.cfl = cfl;
  candidate.cfl_euler = cfl_euler;
  candidate.euler_steps = euler_steps;
  std::string limits_message;
  if (!ValidateCouetteLimits(candidate, &limits_message)) {
    validation.errors.push_back(limits_message);
    return validation;
  }
  *config = candidate;
  config->solver_type = solver->second;
  config->fim = fim;
  config->text_entries = snapshot.entries;
  validation.valid = true;
  return validation;
}

CouetteResult SolveCouette(const CouetteConfig& config) {
  return SolveCouetteInternal(config, NULL);
}

CouetteResult SolveCouette(const ConfigSnapshot& snapshot) {
  CouetteConfig config;
  const ConfigValidation validation = BuildCouetteConfig(snapshot, &config);
  if (!validation.valid) {
    CouetteResult result;
    result.status = CouetteStatus::InvalidConfig;
    result.message = validation.Message();
    return result;
  }
  return SolveCouette(config);
}

CouetteTask::CouetteTask(const CouetteConfig& config,
                         const std::string& workspace,
                         const std::string& resolved_config_path)
    : config_(config), workspace_(workspace),
      resolved_config_path_(resolved_config_path),
      status_(CouetteStatus::Pending), iteration_(0),
      residual_(std::numeric_limits<double>::quiet_NaN()),
      progress_elapsed_nanoseconds_(0),
      stop_requested_(false) {
  result_.config = config;
  result_.workspace = workspace;
  result_.resolved_config_path = resolved_config_path;
  result_.status = CouetteStatus::Pending;
  result_.message = "Pending";
}

CouetteTask::~CouetteTask() {
  RequestStop();
  Wait();
}

CouetteStatus CouetteTask::status() const {
  return status_.load();
}

CouetteProgress CouetteTask::progress() const {
  std::lock_guard<std::mutex> lock(result_mutex_);
  CouetteProgress snapshot;
  snapshot.iteration = iteration_.load();
  snapshot.residual = residual_.load();
  snapshot.elapsed_seconds = static_cast<double>(
      progress_elapsed_nanoseconds_.load()) / 1.0e9;
  return snapshot;
}

unsigned int CouetteTask::iteration() const {
  return progress().iteration;
}

double CouetteTask::residual() const {
  return progress().residual;
}

double CouetteTask::elapsed_seconds() const {
  return progress().elapsed_seconds;
}

const std::string& CouetteTask::workspace() const {
  return workspace_;
}

const std::string& CouetteTask::resolved_config_path() const {
  return resolved_config_path_;
}

void CouetteTask::RequestStop() {
  stop_requested_.store(true);
}

bool CouetteTask::WaitFor(std::chrono::milliseconds timeout) {
  if (timeout.count() < 0) return false;
  std::unique_lock<std::mutex> lock(completion_mutex_);
  return completion_cv_.wait_for(lock, timeout, [this]() {
    const CouetteStatus current = status_.load();
    return current != CouetteStatus::Pending && current != CouetteStatus::Running;
  });
}

void CouetteTask::Wait() {
  if (worker_.joinable()) worker_.join();
}

CouetteResult CouetteTask::GetResult() const {
  std::lock_guard<std::mutex> lock(result_mutex_);
  CouetteResult snapshot = result_;
  snapshot.status = status_.load();
  if (snapshot.status == CouetteStatus::Pending || snapshot.status == CouetteStatus::Running) {
    snapshot.x.clear();
    snapshot.density.clear();
    snapshot.temperature.clear();
    snapshot.velocity.clear();
    snapshot.stress_moments.clear();
    snapshot.heat_flux.clear();
    snapshot.residual.clear();
    snapshot.message = snapshot.status == CouetteStatus::Pending ? "Pending" : "Running";
  }
  return snapshot;
}

void CouetteTask::Run() {
  const long long started_nanoseconds =
      std::chrono::duration_cast<std::chrono::nanoseconds>(
          std::chrono::steady_clock::now().time_since_epoch()).count();
  progress_elapsed_nanoseconds_.store(0);
  status_.store(CouetteStatus::Running);
  CouetteResult completed = SolveCouetteInternal(
      config_, &stop_requested_,
      [this, started_nanoseconds](unsigned int iteration, double residual) {
        const long long now_nanoseconds =
            std::chrono::duration_cast<std::chrono::nanoseconds>(
                std::chrono::steady_clock::now().time_since_epoch()).count();
        std::lock_guard<std::mutex> lock(result_mutex_);
        iteration_.store(iteration);
        residual_.store(residual);
        progress_elapsed_nanoseconds_.store(now_nanoseconds - started_nanoseconds);
      });
  completed.workspace = workspace_;
  completed.resolved_config_path = resolved_config_path_;
  {
    std::lock_guard<std::mutex> lock(result_mutex_);
    result_ = completed;
  }
  status_.store(completed.status);
  completion_cv_.notify_all();
}

std::shared_ptr<CouetteTask> SubmitCouette(const CouetteConfig& config) {
  std::shared_ptr<CouetteTask> task(new CouetteTask(config));
  task->worker_ = std::thread(&CouetteTask::Run, task.get());
  return task;
}

namespace {

bool EnsureTaskRoot(const std::string& root, std::string* error) {
  struct stat state;
  if (stat(root.c_str(), &state) == 0) {
    if (S_ISDIR(state.st_mode)) return true;
    if (error != NULL) *error = "task workspace root is not a directory: " + root;
    return false;
  }
  if (mkdir(root.c_str(), 0755) == 0) return true;
  if (error != NULL) {
    *error = "cannot create task workspace root: " + root +
             " (" + std::strerror(errno) + ")";
  }
  return false;
}

bool FreezeSnapshot(const ConfigSnapshot& snapshot,
                    std::string* workspace,
                    std::string* resolved_config_path,
                    std::string* error) {
  const char* configured_root = std::getenv("HYMOS_RUNS_ROOT");
  const std::string root =
      configured_root != NULL && configured_root[0] != '\0'
          ? configured_root : "/tmp/hymos_baltamatica_runs";
  if (!EnsureTaskRoot(root, error)) return false;

  std::string pattern = root + "/Couette_task_XXXXXX";
  std::vector<char> writable(pattern.begin(), pattern.end());
  writable.push_back('\0');
  char* created = mkdtemp(writable.data());
  if (created == NULL) {
    if (error != NULL) {
      *error = "cannot create unique task workspace under " + root +
               " (" + std::strerror(errno) + ")";
    }
    return false;
  }

  const std::string directory(created);
  const std::string resolved = directory + "/input.resolved.txt";
  std::ofstream output(resolved.c_str(), std::ios::binary);
  output.write(snapshot.text.data(),
               static_cast<std::streamsize>(snapshot.text.size()));
  output.close();
  if (!output) {
    if (error != NULL) *error = "cannot write frozen configuration: " + resolved;
    return false;
  }

  if (workspace != NULL) *workspace = directory;
  if (resolved_config_path != NULL) *resolved_config_path = resolved;
  return true;
}

}  // namespace

std::shared_ptr<CouetteTask> SubmitCouette(const ConfigSnapshot& snapshot,
                                           ConfigValidation* validation) {
  CouetteConfig config;
  ConfigValidation checked = BuildCouetteConfig(snapshot, &config);
  std::string workspace;
  std::string resolved_config_path;
  if (checked.valid) {
    std::string freeze_error;
    if (!FreezeSnapshot(snapshot, &workspace, &resolved_config_path,
                        &freeze_error)) {
      checked.valid = false;
      checked.errors.push_back(freeze_error);
    }
  }
  if (validation != NULL) *validation = checked;
  if (checked.valid) {
    config.legacy_distribution_output_path = workspace + "/DisSol1th.dat";
    std::shared_ptr<CouetteTask> task(
        new CouetteTask(config, workspace, resolved_config_path));
    task->worker_ = std::thread(&CouetteTask::Run, task.get());
    return task;
  }

  std::shared_ptr<CouetteTask> task(new CouetteTask(config));
  {
    std::lock_guard<std::mutex> lock(task->result_mutex_);
    task->result_.status = CouetteStatus::InvalidConfig;
    task->result_.message = checked.Message();
  }
  task->status_.store(CouetteStatus::InvalidConfig);
  return task;
}

}  // namespace engine
}  // namespace hymos
